spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # use create once if needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show-sql: true
server:
  port: 8083

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/auth_app
#    username: root
#    password: root
#  #JPA and Hibernate configuration
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#      show-sql: true
#
#    server:
#      port: 8083

      #database Connection

#      hikari:
#       pool-name: HikariCP
#       maximum-pool-size : 5
#       connection-timeout : 10000
#       idle-timeout : 600000
#       max-lifetime : 1800000
#       validation-timeout : 1800000
#       leak-detection-threshold : 0
#       initialization-fail-timeout : -1













